### ISSUE TITLE
s3migration: download and upload file by chunks

### ISSUE THREAD

**Issue by boddumanohar** [0chain/s3-migration#67]
during s3migration, we currently download all the file and then upload the file. This will become problematic for files of larges size. 

So we should be able to download the from s3 in chunks and upload to Zus Storage

**Comment by Roshan-Mehta** [comment]
gosdk is not able to capable of chunks upload. It uploads the data in chunks internally but it does require complete file before creating chunk upload. The enhancement in gosdk will be done as part of [this](https://github.com/0chain/gosdk/issues/1067) issue.

**Comment by Roshan-Mehta** [comment]
Performance test
download in memory vs in file system
https://docs.google.com/document/d/1dBV-qioTRXAU7DduycIpVasf_s6WffcO5_ZyrSIIROw/edit#heading=h.wgwmh7eyhn0k
