### ISSUE TITLE
s3 migration duplicate suffix is not working properly

### ISSUE THREAD

**Issue by shalinikum** [0chain/s3-migration#74]
suppose --dup-suffix = "_copy"
we have a bucket called dummy_bucket and in that bucket we have abc.txt.
with skip=2 in first attempt it should migrate as abc.txt but in second attempt it should be abc_copy.txt. 

But right now I am seeing in second attempt the file name is abc_copt_<random_number>.txt

either fix the ./s3mgrt migrate --help output or fix above isssue.

**Comment by boddumanohar** [comment]
fixed by: https://github.com/0chain/s3-migration/pull/77
