### ISSUE TITLE
s3migration fails migrating other files if the filename length is greater than 100 chars

### ISSUE THREAD

**Issue by boddumanohar** [0chain/s3-migration#88]
lets say i have 3 files in the s3 bucket
1. a.txt
2. b.txt
3. Test0S3MigrationAlternatePart2-Should_not_pass_when_filename_size_is_more_than_100_character.txt

when I start the migration, it fails to migrate all 3 files. 

expected: 

it shouldn't fail migration of other files. It should only fail the migration of the file with name greater than 100 chars

**Comment by sunilmhta** [comment]
Fixing it by trimming the long file names to 100 chars . Raised  PR: #91 for the same. 
Also, I have tested it with two scenarios:
1. **Simple migrate without any other flags turned on**: This migrated all the files from the s3 bucket to the 0chain allocation   including the files with long file names. In the allocation, the file name would be changed to shorter file names.
2. **Migrate with delete-source as true**: As in first test, migration was done successfully and it also deleted the files in s3 bucket successfully.
